# Generated by Django 3.1 on 2022-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='Add the original URL that you want to shorten.')),
                ('key', models.TextField(help_text='Add any random characters of your choice to shorten it.', unique=True)),
            ],
        ),
    ]
